#!/bin/bash
#######################################################
# Is this device on an exclusion list?
# 2021-02-17-01
# (c) 2019-2021 @doron - CC BY-SA 4.0

IsExcluded () {

##  return 1	#***** Temporary placeholder ****

  local DEV=${1#'/dev/'}
  local MODEL=$(cat /sys/block/$DEV/device/model | Trim)
  local REV=$(cat /sys/block/$DEV/device/rev | Trim)
  local VENDOR=$(cat /sys/block/$DEV/device/vendor | Trim)
  local CTRLID=$(GetCtrlID $DEV)		# PCI ID

# This is the exception list. If it becomes larger - should improve search

##  [[ "$MODEL" =~ ^ST[0-9]+NM[0-9]+3$ ]] ||	# Constellation ES.3
##  [[ "$VENDOR" == "SEAGATE" ]] ||
  [[ "$MODEL" =~ ^HUC[0-9]+CSS600$ ]] ||	# Hitachi HUCnnnnCSS600
  [[ "$MODEL" =~ X422_[A-Z0-9]{5}600A10 ]] ||	# Netapp rebrands of the Hitachi
  [[ "${MODEL}:${REV}" =~ MB8000JFECQ:HPD[4-7] ]] ||	# HPE MB8000JFECQ
  [[ "${MODEL}:${REV}" =~ MBF2300RC:DA07 ]] ||	# Toshiba MBF2300RC (20201223)
  [[ "$CTRLID" == "1000:0087:1590:0042" ]] || 	# HPE H221 (9207-8e) (20210217)
  [[ "$CTRLID" == "9005:8076:15d9:1600" ]] || 	# SM/Adaptec (20210326) (hattip @half)
  false						# End the || chain

}
#######################################################
